### ISSUE TITLE
Delete multiple files on GitHub

### ISSUE THREAD

**Issue by Syht** [Syht/StochPong#20]
As the title states, I want to know hows to delete multiple files on github! If I get it right, I need to use a git command prompt (I already installed git and I have git bash now).
But I'm not sure what to do now. My exact question would be "how to delete multiple files at the same time on github?" because when you want to delete a file on github, you need to do it one by one. Since we got a lot of files to delete (in datadir), I thought I could find a better way to do so.

**Comment by laurentperrinet** [comment]
it is hard (if not impossible) to delete files from the *history* on github - but you can remove files from your current version and they will be removed in all up-to-date versions.

**Comment by Syht** [comment]
You just enlightened the problem I got: I don't use github desktop thus I don't have an exact copy of the repo on my computer. I just installed GitHub Desktop but the fact is that I have some files that I don't want to upload to github (because they are irrelevant, I keep them just in case).
Now it doesn't want to push my file to the repo because it want me to pull the repo before!
![image](https://user-images.githubusercontent.com/27817164/27798243-cb05cc72-6010-11e7-8416-656f4a1e8a5b.png)

and when I try to pull:
![image](https://user-images.githubusercontent.com/27817164/27798346-2fbff7d2-6011-11e7-8a6c-83a721c57b6d.png)


I'll deal with it tomorrow and I'll keep you in touch.

**Comment by Syht** [comment]
Dealt with! I know how to use GitHub Desktop now and I pushed all my StochPong file into GitHub.

In datadir/pilot, you can find all the pilots I recorded with an inf.txt file in which I noted which set of levels each user has played.

I close the Issue.
