### ISSUE TITLE
Heat maps

### ISSUE THREAD

**Issue by Syht** [Syht/StochPong#8]
There are several possibilities for us to build heat maps:
- Ogama (the one I'm learning to use at the moment)
- using Matplotlib in python
- other softwares

Laurent, do you have any knowledge about those? And any advice to give me?

I didn't find any tutorial to learn Ogama, thus I try to learn by practice but some things seem odd. I tried to draw a heat map from some gaze data I collected with Eye Tribe, but I only obtained three dots so far!

![image](https://cloud.githubusercontent.com/assets/27817164/26551971/5e26fb36-4485-11e7-8e49-c417d1475ce8.png)

I'll post any further progress I make later on.

Edit: I found what I did wrong -> I set the time in (ms) instead of (s)

Edit2: I managed to generate the fixation map and the heat map for some gaze data that I recorded.
![image](https://cloud.githubusercontent.com/assets/27817164/26585872/c0dd798a-454d-11e7-9b91-9ecbb0278fb4.png)
![image](https://cloud.githubusercontent.com/assets/27817164/26585910/df765b0a-454d-11e7-994d-148502798e23.png)

There's still something I didn't manage to do -> to display an image of the game in the background of the heatmap.

**Comment by laurentperrinet** [comment]
Have you also tried using Matplotlib in python? this is usually very simple...
